eureka:
  instance:
    hostname: academic-guidance-service.herokuapp.com
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://guidance-discovery-service.herokuapp.com/eureka/
    region: default
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: academic-guidance-service
  datasource:
    url: jdbc:postgresql://ec2-44-206-137-96.compute-1.amazonaws.com:5432/dds22823a1kcec
    username: bgiwgdfbrnsnuz
    password: 1ae77a00e1b462ffb7d53b5622fc89bbd495c954f7d206645643a923e145eb4f
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop