spring:
  application:
    name: student-consultation-service
  datasource:
    url: jdbc:postgresql://ec2-54-152-28-9.compute-1.amazonaws.com:5432/ds2452uku3go7
    username: ydarouiesykgfm
    password: f739610cd21c7dbe10bb9b9ac79e4eb5147f1a6f51d4800a887b5c4698634100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop